; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
DefaultDirName="C:\xampp\htdocs\Proyecto Cerveceria"


[Files]
Source: "C:\xampp\htdocs\Proyecto Cerveceria"; DestDir: "{app}"; Flags: recursesubdirs
